const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path');require('dotenv').config();
const db=require('./db'),auth=require('./auth'),{validate}=require('./stock');const app=express();app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'../frontend')));
const ok=(res,data={})=>res.json({success:true,...data});const bad=(res,s,m)=>res.status(s).json({success:false,message:m});const ref=p=>p+'-'+Date.now().toString().slice(-8);
app.post('/api/auth/signup',async(req,res)=>{try{const{name,email,password,role='Warehouse Staff'}=req.body;if(!name||!email||!password)return bad(res,400,'Required fields missing');const h=await bcrypt.hash(password,10);const[r]=await db.query('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)',[name,email.toLowerCase(),h,role]);ok(res,{id:r.insertId})}catch(e){bad(res,e.code==='ER_DUP_ENTRY'?409:500,e.code==='ER_DUP_ENTRY'?'Email already exists':e.message)}});
app.post('/api/auth/login',async(req,res)=>{try{const[r]=await db.query('SELECT * FROM users WHERE email=?',[String(req.body.email||'').toLowerCase()]);if(!r.length||!await bcrypt.compare(req.body.password,r[0].password_hash))return bad(res,401,'Invalid email or password');const u=r[0],token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'8h'});ok(res,{token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){bad(res,500,e.message)}});
const otp=new Map();app.post('/api/auth/forgot-password',async(req,res)=>{const email=String(req.body.email||'').toLowerCase();const[r]=await db.query('SELECT id FROM users WHERE email=?',[email]);if(!r.length)return bad(res,404,'Email not found');const code=String(Math.floor(100000+Math.random()*900000));otp.set(email,{code,exp:Date.now()+600000});ok(res,{developmentOtp:code})});
app.post('/api/auth/reset-password',async(req,res)=>{try{const email=String(req.body.email||'').toLowerCase(),x=otp.get(email);if(!x||x.exp<Date.now()||x.code!==String(req.body.otp))return bad(res,400,'Invalid or expired OTP');await db.query('UPDATE users SET password_hash=? WHERE email=?',[await bcrypt.hash(req.body.password,10),email]);otp.delete(email);ok(res)}catch(e){bad(res,500,e.message)}});
app.get('/api/categories',auth,async(req,res)=>{const[r]=await db.query('SELECT * FROM categories ORDER BY name');ok(res,{categories:r})});app.post('/api/categories',auth,async(req,res)=>{try{const[r]=await db.query('INSERT INTO categories(name,description) VALUES(?,?)',[req.body.name,req.body.description||null]);ok(res,{id:r.insertId})}catch(e){bad(res,500,e.message)}});
app.get('/api/warehouses',auth,async(req,res)=>{const[r]=await db.query('SELECT * FROM warehouses ORDER BY name');ok(res,{warehouses:r})});app.post('/api/warehouses',auth,async(req,res)=>{try{const[r]=await db.query('INSERT INTO warehouses(name,code,address) VALUES(?,?,?)',[req.body.name,req.body.code,req.body.address||null]);ok(res,{id:r.insertId})}catch(e){bad(res,500,e.message)}});
app.get('/api/locations',auth,async(req,res)=>{const[r]=await db.query('SELECT l.*,w.name warehouse_name FROM locations l JOIN warehouses w ON w.id=l.warehouse_id ORDER BY w.name,l.name');ok(res,{locations:r})});
app.get('/api/products',auth,async(req,res)=>{const[r]=await db.query('SELECT p.*,c.name category_name,COALESCE(SUM(sl.quantity),0) total_stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN stock_levels sl ON sl.product_id=p.id GROUP BY p.id ORDER BY p.name');ok(res,{products:r})});
app.post('/api/products',auth,async(req,res)=>{try{const{name,sku,category_id,unit_of_measure='pcs',reorder_level=0,description}=req.body;if(!name||!sku||![/^[A-Z0-9-]+$/.test(String(sku).toUpperCase())])return bad(res,400,'Invalid product/SKU');const[r]=await db.query('INSERT INTO products(name,sku,category_id,unit_of_measure,reorder_level,description) VALUES(?,?,?,?,?,?)',[name,String(sku).toUpperCase(),category_id||null,unit_of_measure,reorder_level,description||null]);ok(res,{id:r.insertId})}catch(e){bad(res,e.code==='ER_DUP_ENTRY'?409:500,e.code==='ER_DUP_ENTRY'?'SKU already exists':e.message)}});
app.put('/api/products/:id',auth,async(req,res)=>{try{await db.query('UPDATE products SET name=?,sku=?,category_id=?,unit_of_measure=?,reorder_level=?,description=? WHERE id=?',[req.body.name,String(req.body.sku).toUpperCase(),req.body.category_id||null,req.body.unit_of_measure,req.body.reorder_level,req.body.description||null,req.params.id]);ok(res)}catch(e){bad(res,500,e.message)}});
app.delete('/api/products/:id',auth,async(req,res)=>{try{await db.query('DELETE FROM products WHERE id=?',[req.params.id]);ok(res)}catch(e){bad(res,500,'Product cannot be deleted because it is referenced by inventory history')}});
app.get('/api/dashboard/summary',auth,async(req,res)=>{try{const[[s]]=await db.query('SELECT COALESCE(SUM(quantity),0) n FROM stock_levels');const[[p]]=await db.query('SELECT COUNT(*) n FROM products');const[[l]]=await db.query('SELECT COUNT(*) n FROM (SELECT p.id,COALESCE(SUM(sl.quantity),0) q FROM products p LEFT JOIN stock_levels sl ON sl.product_id=p.id GROUP BY p.id HAVING q<=MAX(p.reorder_level)) x');const[[r]]=await db.query("SELECT COUNT(*) n FROM operations WHERE operation_type='RECEIPT' AND status IN('DRAFT','WAITING','READY')");const[[d]]=await db.query("SELECT COUNT(*) n FROM operations WHERE operation_type='DELIVERY' AND status IN('DRAFT','WAITING','READY')");const[[t]]=await db.query("SELECT COUNT(*) n FROM operations WHERE operation_type='TRANSFER' AND status IN('DRAFT','WAITING','READY')");ok(res,{summary:{totalStock:s.n,totalProducts:p.n,lowStock:l.n,pendingReceipts:r.n,pendingDeliveries:d.n,transfersScheduled:t.n}})}catch(e){bad(res,500,e.message)}});
app.get('/api/dashboard/alerts',auth,async(req,res)=>{const[r]=await db.query('SELECT p.*,COALESCE(SUM(sl.quantity),0) current_stock FROM products p LEFT JOIN stock_levels sl ON sl.product_id=p.id GROUP BY p.id HAVING current_stock<=p.reorder_level ORDER BY current_stock');ok(res,{alerts:r})});
app.get('/api/dashboard/operations',auth,async(req,res)=>{try{let w='1=1',a=[];if(req.query.type&&req.query.type!=='ALL'){w+=' AND o.operation_type=?';a.push(req.query.type)}if(req.query.status&&req.query.status!=='ALL'){w+=' AND o.status=?';a.push(req.query.status)}const[r]=await db.query(`SELECT o.*,oi.quantity,p.name product_name,p.unit_of_measure,COALESCE(l2.name,l1.name,'-') location_name FROM operations o JOIN operation_items oi ON oi.operation_id=o.id JOIN products p ON p.id=oi.product_id LEFT JOIN locations l1 ON l1.id=o.source_location_id LEFT JOIN locations l2 ON l2.id=o.destination_location_id WHERE ${w} ORDER BY o.created_at DESC LIMIT 50`,a);ok(res,{operations:r})}catch(e){bad(res,500,e.message)}});
async function create(req,res,type,prefix){try{const{source_location_id=null,destination_location_id=null,partner_name=null,notes=null,items=[]}=req.body;if(!items.length)return bad(res,400,'Add at least one item');const c=await db.getConnection();try{await c.beginTransaction();const reference=ref(prefix);const[r]=await c.query('INSERT INTO operations(operation_type,reference_number,status,source_location_id,destination_location_id,partner_name,notes,created_by) VALUES(?,?,?,?,?,?,?,?)',[type,reference,'READY',source_location_id,destination_location_id,partner_name,notes,req.user.id]);for(const x of items)await c.query('INSERT INTO operation_items(operation_id,product_id,quantity,unit) SELECT ?,id,?,unit_of_measure FROM products WHERE id=?',[r.insertId,x.quantity,x.product_id]);await c.commit();ok(res,{id:r.insertId,reference})}catch(e){await c.rollback();throw e}finally{c.release()}}catch(e){bad(res,500,e.message)}}
for(const [route,type,prefix] of [['receipts','RECEIPT','REC'],['deliveries','DELIVERY','DEL'],['transfers','TRANSFER','TRF'],['adjustments','ADJUSTMENT','ADJ']]){app.get('/api/operations/'+route,auth,async(req,res)=>{const[r]=await db.query('SELECT o.*,l1.name source_location,l2.name destination_location FROM operations o LEFT JOIN locations l1 ON l1.id=o.source_location_id LEFT JOIN locations l2 ON l2.id=o.destination_location_id WHERE o.operation_type=? ORDER BY o.created_at DESC',[type]);ok(res,{operations:r})});app.post('/api/operations/'+route,auth,(req,res)=>create(req,res,type,prefix))}
app.post('/api/operations/:id/validate',auth,async(req,res)=>{try{await validate(req.params.id,req.user.id);ok(res)}catch(e){bad(res,e.code==='STOCK'?409:400,e.message)}});app.post('/api/operations/:id/cancel',auth,async(req,res)=>{await db.query("UPDATE operations SET status='CANCELED' WHERE id=? AND status<>'DONE'",[req.params.id]);ok(res)});
app.get('/api/ledger',auth,async(req,res)=>{const[r]=await db.query('SELECT sl.*,p.name product_name,p.sku,lf.name from_location,lt.name to_location,u.name user_name FROM stock_ledger sl JOIN products p ON p.id=sl.product_id LEFT JOIN locations lf ON lf.id=sl.from_location_id LEFT JOIN locations lt ON lt.id=sl.to_location_id LEFT JOIN users u ON u.id=sl.created_by ORDER BY sl.created_at DESC LIMIT 200');ok(res,{ledger:r})});
app.get('/api/profile',auth,async(req,res)=>{const[r]=await db.query('SELECT id,name,email,role,created_at FROM users WHERE id=?',[req.user.id]);ok(res,{user:r[0]})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/dashboard.html')));
app.listen(process.env.PORT||5000,()=>console.log('StockSense: http://localhost:'+ (process.env.PORT||5000)));
